/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule Home_User.flow
 * @generated SignedSource<<c2aac86dcd7b8d89a8f3878e5b572ad0>>
 * @flow
 */

'use strict';

export type Home_User = {
  username?: ?string;
};
